# Generated by Django 3.0 on 2020-10-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='item',
        ),
    ]
