# Generated by Django 3.0 on 2020-10-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_post_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='item',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
