# Generated by Django 3.0 on 2020-10-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_information',
            field=models.CharField(choices=[('Apartments', 'Apartments'), ('Hilltop House', 'Hilltop House'), ('Holmes Hall', 'Holmes Hall'), ('Leitzell Hall', 'Leitzell Hall'), ('Oyaron House', 'Oyaron House'), ('Pine Lake Housing', 'Pine Lake Housing'), ('Saxton Hall', 'Saxton Hall'), ('Smith Hall', 'Smith Hall'), ('Townhouses', 'Townhouses'), ('Van Ess Hall', 'Van Ess Hall'), ('Wilder Hall', 'Wilder Hall')], max_length=200),
        ),
    ]
